#!/bin/bash
rm -f ./.babelrc.json
rm -f ./.env
rm -f ./.env.example
rm -f ./.env.production.example
rm -f ./.eslintrc.json
rm -f ./.gitignore
rm -f ./.trunk/configs/.markdownlint.yaml
rm -f ./.prettierrc
rm -f ./.trunk/configs/.shellcheckrc
rm -f ./.trunk/.gitignore
rm -f ./.vercelignore
rm -f ./.trunk/configs/.yamllint.yaml
rm -f ./public/css/admin.css
rm -f ./public/pages/admin.html
rm -f ./public/frontend/admin.js
rm -f ./public/src/frontend/admin.js
rm -f ./public/frontend/services/api.js
rm -f ./public/src/frontend/services/api.js
rm -f ./public/app/middleware/auth.js
rm -f ./public/frontend/auth.js
rm -f ./public/src/app/middleware/auth.js
rm -f ./public/src/frontend/auth.js
rm -f ./public/css/carousel.css
rm -f ./public/models/Database.js
rm -f ./public/src/models/Database.js
rm -f ./public/src/types/globals.js
rm -f ./public/types/globals.js
rm -f ./public/images/hero-flowers.jpg
rm -f ./public/images/hero-flowers.webp
rm -f ./public/controllers/ImageController.js
rm -f ./public/src/controllers/ImageController.js
rm -f ./public/app/routes/imageRoutes.js
rm -f ./public/src/app/routes/imageRoutes.js
rm -f ./public/services/ImageService.js
rm -f ./public/src/services/ImageService.js
rm -f ./public/index.html
rm -f ./public/frontend/types/index.js
rm -f ./public/src/frontend/types/index.js
rm -f ./public/frontend/utils/logger.js
rm -f ./public/src/frontend/utils/logger.js
rm -f ./public/controllers/LogsController.js
rm -f ./public/src/controllers/LogsController.js
rm -f ./public/app/routes/logsRoutes.js
rm -f ./public/src/app/routes/logsRoutes.js
rm -f ./public/frontend/main.js
rm -f ./public/src/frontend/main.js
rm -f ./public/controllers/OccasionsController.js
rm -f ./public/src/controllers/OccasionsController.js
rm -f ./public/app/routes/occasionsRoutes.js
rm -f ./public/src/app/routes/occasionsRoutes.js
rm -f ./public/services/OccasionsService.js
rm -f ./public/src/services/OccasionsService.js
rm -f ./public/controllers/OrderController.js
rm -f ./public/src/controllers/OrderController.js
rm -f ./public/app/routes/orderRoutes.js
rm -f ./public/src/app/routes/orderRoutes.js
rm -f ./public/services/OrderService.js
rm -f ./public/src/services/OrderService.js
rm -f ./public/images/placeholder-product.jpg
rm -f ./public/images/placeholder-product.webp
rm -f ./public/controllers/ProductController.js
rm -f ./public/src/controllers/ProductController.js
rm -f ./public/css/product-detail.css
rm -f ./public/pages/product-detail.html
rm -f ./public/app/routes/productRoutes.js
rm -f ./public/src/app/routes/productRoutes.js
rm -f ./public/services/ProductService.js
rm -f ./public/src/services/ProductService.js
rm -f ./README.md
rm -f ./.vercel/README.txt
rm -f ./public/src/utils/schema-extractor.js
rm -f ./public/utils/schema-extractor.js
rm -f ./public/app/routes/schemaRoutes.js
rm -f ./public/src/app/routes/schemaRoutes.js
rm -f ./public/frontend/scroll-effects-fix.js
rm -f ./public/src/frontend/scroll-effects-fix.js
rm -f ./public/app/server.js
rm -f ./public/src/app/server.js
rm -f ./public/src/utils/serverLogger.js
rm -f ./public/utils/serverLogger.js
rm -f ./public/src/types/shared.js
rm -f ./public/types/shared.js
rm -f ./public/config/supabase.js
rm -f ./public/src/config/supabase.js
rm -f ./public/config/supabase-types.js
rm -f ./public/src/config/supabase-types.js
rm -f ./public/config/swagger.js
rm -f ./public/src/config/swagger.js
rm -f ./public/frontend/types.js
rm -f ./public/src/frontend/types.js
rm -f ./public/controllers/UserController.js
rm -f ./public/src/controllers/UserController.js
rm -f ./public/app/routes/userRoutes.js
rm -f ./public/src/app/routes/userRoutes.js
rm -f ./public/frontend/users-admin.js
rm -f ./public/src/frontend/users-admin.js
rm -f ./public/services/UserService.js
rm -f ./public/src/services/UserService.js
